public class IndexNameTests
{
    static DbContextOptions CreateOptions(bool? createIndexes = true) =>
        new DbContextOptionsBuilder()
            .UseSqlServer("Server=.;Database=Test;Trusted_Connection=True")
            .UseDefaultOrderBy(createIndexes: createIndexes)
            .Options;

    [Test]
    public async Task AutoGeneratedIndexName_WithinLimit_Succeeds()
    {
        // Should not throw - entity name is short
        using var context = new ContextWithShortEntityName(CreateOptions());
        _ = context.Model;

        // Verify the index was created with auto-generated name
        var entityType = context.Model.FindEntityType(typeof(ShortEntity))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        await Assert.That(index).IsNotNull();
        await Assert.That(index?.GetDatabaseName()).IsEqualTo("IX_ShortEntity_DefaultOrder");
    }

    [Test]
    public async Task AutoGeneratedIndexName_ExceedsLimit_ThrowsWithHelpfulMessage()
    {
        var exception = Assert.ThrowsExactly<Exception>(() =>
        {
            using var context = new ContextWithLongEntityName(CreateOptions());
            _ = context.Model;
        })!;

        await Assert.That(exception.Message).Contains("exceeds the maximum length of 128");
        await Assert.That(exception.Message).Contains("WithIndexName()");
    }

    [Test]
    public async Task CustomIndexName_WithinLimit_Succeeds()
    {
        // Should not throw
        using var context = new ContextWithCustomIndexName(CreateOptions());
        _ = context.Model;

        // Verify the index was created with custom name
        var entityType = context.Model.FindEntityType(typeof(EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        await Assert.That(index).IsNotNull();
        await Assert.That(index?.GetDatabaseName()).IsEqualTo("IX_LongEntity_Order");
    }

    [Test]
    public async Task CustomIndexName_ExceedsLimit_ThrowsArgumentException()
    {
        var exception = Assert.ThrowsExactly<ArgumentException>(() =>
        {
            using var context = new ContextWithTooLongCustomIndexName(CreateOptions());
            _ = context.Model;
        })!;

        await Assert.That(exception.Message).Contains("exceeds maximum length of 128");
    }

    [Test]
    public async Task CustomIndexName_NullOrEmpty_ThrowsArgumentException()
    {
        var exception = Assert.ThrowsExactly<ArgumentException>(() =>
        {
            using var context = new ContextWithEmptyCustomIndexName(CreateOptions());
            _ = context.Model;
        })!;

        await Assert.That(exception.Message).Contains("cannot be null or whitespace");
    }

    [Test]
    public async Task CreateIndexes_False_NoIndexCreated()
    {
        using var context = new ContextWithIndexCreationDisabled(CreateOptions(createIndexes: false));
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(ShortEntity))!;
        var indexes = entityType.GetIndexes().ToList();
        await Assert.That(indexes).IsEmpty();
    }

    [Test]
    public async Task CreateIndexes_False_WithIndexName_Throws()
    {
        var exception = Assert.ThrowsExactly<Exception>(() =>
        {
            using var context = new ContextWithIndexCreationDisabledAndWithIndexName(CreateOptions(createIndexes: false));
            _ = context.Model;
        })!;

        await Assert.That(exception.Message).Contains("index creation is disabled");
    }

    [Test]
    public async Task WithIndexName_CanBeChainedWithThenBy()
    {
        // Should not throw
        using var context = new ContextWithChainedIndexName(CreateOptions());
        _ = context.Model;

        // Verify the index was created with custom name and has all properties
        var entityType = context.Model.FindEntityType(typeof(MultiPropertyEntity))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        await Assert.That(index).IsNotNull();
        await Assert.That(index?.GetDatabaseName()).IsEqualTo("IX_Multi_Custom");
        await Assert.That(index?.Properties.Select(p => p.Name)).IsEquivalentTo(["Category", "Priority"]);
    }

    [Test]
    public async Task StringWithNoMaxLength_SkipsIndex()
    {
        using var context = new ContextWithStringNoMaxLength(CreateOptions());
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(StringNoMaxLengthEntity))!;
        var indexes = entityType.GetIndexes().ToList();
        await Assert.That(indexes).IsEmpty();
    }

    [Test]
    public async Task StringWithLargeMaxLength_SkipsIndex()
    {
        using var context = new ContextWithStringLargeMaxLength(CreateOptions());
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(StringLargeMaxLengthEntity))!;
        var indexes = entityType.GetIndexes().ToList();
        await Assert.That(indexes).IsEmpty();
    }

    [Test]
    public async Task StringWithSmallMaxLength_CreatesIndex()
    {
        using var context = new ContextWithStringSmallMaxLength(CreateOptions());
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(StringSmallMaxLengthEntity))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        await Assert.That(index).IsNotNull();
    }

    [Test]
    public async Task NonStringProperty_AlwaysCreatesIndex()
    {
        using var context = new ContextWithNonStringOrder(CreateOptions());
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(NonStringOrderEntity))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        await Assert.That(index).IsNotNull();
    }

    [Test]
    public async Task CompositeIndex_WithStringNoMaxLength_SkipsIndex()
    {
        // Even if one property in a composite index is a string without max length,
        // the entire index is skipped
        using var context = new ContextWithMixedStringNoMaxLength(CreateOptions());
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(MixedStringNoMaxLengthEntity))!;
        var indexes = entityType.GetIndexes().ToList();
        await Assert.That(indexes).IsEmpty();
    }

    [Test]
    public async Task SqliteProvider_StringWithNoMaxLength_CreatesIndex()
    {
        // SQLite has no index key size limit, so strings without max length should still get indexes
        var options = new DbContextOptionsBuilder()
            .UseSqlite("Data Source=:memory:")
            .UseDefaultOrderBy()
            .Options;

        using var context = new ContextWithStringNoMaxLength(options);
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(StringNoMaxLengthEntity))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        await Assert.That(index).IsNotNull();
    }

    [Test]
    public async Task OrderByAndExplicitIndex_ProducesTwoDistinctIndexes()
    {
        using var context = new ContextWithOrderByAndExplicitIndex(CreateOptions());
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(EntityWithBothIndexes))!;
        var indexes = entityType.GetIndexes().ToList();
        await Assert.That(indexes).Count().IsEqualTo(2);

        var uniqueIndex = indexes.Single(_ => _.IsUnique);
        await Assert.That(uniqueIndex.Properties.Select(_ => _.Name)).IsEquivalentTo(["Name"]);

        var orderByIndex = indexes.Single(_ => !_.IsUnique);
        await Assert.That(orderByIndex.GetDatabaseName()).IsEqualTo("IX_EntityWithBothIndexes_DefaultOrder");
        await Assert.That(orderByIndex.Properties.Select(_ => _.Name)).IsEquivalentTo(["Name"]);
    }
}

class ContextWithShortEntityName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .Property(_ => _.Name).HasMaxLength(450);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithLongEntityName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix> Entities => Set<EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix>()
            .Property(_ => _.Name).HasMaxLength(450);
        modelBuilder.Entity<EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithCustomIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere> Entities => Set<EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere>()
            .Property(_ => _.Name).HasMaxLength(450);
        modelBuilder.Entity<EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere>()
            .OrderBy(_ => _.Name)
            .WithIndexName("IX_LongEntity_Order");
    }
}

class ContextWithTooLongCustomIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .Property(_ => _.Name).HasMaxLength(450);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name)
            .WithIndexName(new('X', 129)); // 129 characters exceeds limit
    }
}

class ContextWithEmptyCustomIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .Property(_ => _.Name).HasMaxLength(450);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name)
            .WithIndexName("");
    }
}

class ContextWithChainedIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<MultiPropertyEntity> Entities => Set<MultiPropertyEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<MultiPropertyEntity>()
            .Property(_ => _.Category).HasMaxLength(450);
        modelBuilder.Entity<MultiPropertyEntity>()
            .OrderBy(_ => _.Category)
            .ThenBy(_ => _.Priority)
            .WithIndexName("IX_Multi_Custom");
    }
}

class ContextWithIndexCreationDisabled(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithIndexCreationDisabledAndWithIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name)
            .WithIndexName("IX_Custom");
    }
}

class ContextWithStringNoMaxLength(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<StringNoMaxLengthEntity> Entities => Set<StringNoMaxLengthEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<StringNoMaxLengthEntity>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithStringLargeMaxLength(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<StringLargeMaxLengthEntity> Entities => Set<StringLargeMaxLengthEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<StringLargeMaxLengthEntity>()
            .Property(_ => _.Name).HasMaxLength(1000);
        modelBuilder.Entity<StringLargeMaxLengthEntity>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithStringSmallMaxLength(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<StringSmallMaxLengthEntity> Entities => Set<StringSmallMaxLengthEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<StringSmallMaxLengthEntity>()
            .Property(_ => _.Name).HasMaxLength(200);
        modelBuilder.Entity<StringSmallMaxLengthEntity>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithNonStringOrder(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<NonStringOrderEntity> Entities => Set<NonStringOrderEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<NonStringOrderEntity>()
            .OrderBy(_ => _.Priority);
    }
}

class ContextWithMixedStringNoMaxLength(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<MixedStringNoMaxLengthEntity> Entities => Set<MixedStringNoMaxLengthEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<MixedStringNoMaxLengthEntity>()
            .OrderBy(_ => _.Priority)
            .ThenBy(_ => _.Name);
    }
}

public class ShortEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class MultiPropertyEntity
{
    public int Id { get; set; }
    public string Category { get; set; } = "";
    public int Priority { get; set; }
}

public class StringNoMaxLengthEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class StringLargeMaxLengthEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class StringSmallMaxLengthEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class NonStringOrderEntity
{
    public int Id { get; set; }
    public int Priority { get; set; }
    public string Name { get; set; } = "";
}

public class MixedStringNoMaxLengthEntity
{
    public int Id { get; set; }
    public int Priority { get; set; }
    public string Name { get; set; } = "";
}

class ContextWithOrderByAndExplicitIndex(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<EntityWithBothIndexes> Entities => Set<EntityWithBothIndexes>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        var builder = modelBuilder.Entity<EntityWithBothIndexes>();
        builder.Property(_ => _.Name).HasMaxLength(450);
        builder.OrderBy(_ => _.Name);
        builder.HasIndex(_ => _.Name)
            .IsUnique();
    }
}

public class EntityWithBothIndexes
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}
