[TestFixture]
public class IndexNameTests
{
    static DbContextOptions CreateOptions(bool? createIndexes = true) =>
        new DbContextOptionsBuilder()
            .UseSqlServer("Server=.;Database=Test;Trusted_Connection=True")
            .UseDefaultOrderBy(createIndexes: createIndexes)
            .Options;

    [Test]
    public void AutoGeneratedIndexName_WithinLimit_Succeeds()
    {
        // Should not throw - entity name is short
        using var context = new ContextWithShortEntityName(CreateOptions());
        _ = context.Model;

        // Verify the index was created with auto-generated name
        var entityType = context.Model.FindEntityType(typeof(ShortEntity))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        Assert.That(index, Is.Not.Null);
        Assert.That(index?.GetDatabaseName(), Is.EqualTo("IX_ShortEntity_DefaultOrder"));
    }

    [Test]
    public void AutoGeneratedIndexName_ExceedsLimit_ThrowsWithHelpfulMessage()
    {
        var exception = Assert.Throws<InvalidOperationException>(() =>
        {
            using var context = new ContextWithLongEntityName(CreateOptions());
            _ = context.Model;
        })!;

        Assert.That(exception.Message, Does.Contain("exceeds the maximum length of 128"));
        Assert.That(exception.Message, Does.Contain("WithIndexName()"));
    }

    [Test]
    public void CustomIndexName_WithinLimit_Succeeds()
    {
        // Should not throw
        using var context = new ContextWithCustomIndexName(CreateOptions());
        _ = context.Model;

        // Verify the index was created with custom name
        var entityType = context.Model.FindEntityType(typeof(EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        Assert.That(index, Is.Not.Null);
        Assert.That(index?.GetDatabaseName(), Is.EqualTo("IX_LongEntity_Order"));
    }

    [Test]
    public void CustomIndexName_ExceedsLimit_ThrowsArgumentException()
    {
        var exception = Assert.Throws<ArgumentException>(() =>
        {
            using var context = new ContextWithTooLongCustomIndexName(CreateOptions());
            _ = context.Model;
        })!;

        Assert.That(exception.Message, Does.Contain("exceeds maximum length of 128"));
    }

    [Test]
    public void CustomIndexName_NullOrEmpty_ThrowsArgumentException()
    {
        var exception = Assert.Throws<ArgumentException>(() =>
        {
            using var context = new ContextWithEmptyCustomIndexName(CreateOptions());
            _ = context.Model;
        })!;

        Assert.That(exception.Message, Does.Contain("cannot be null or whitespace"));
    }

    [Test]
    public void CreateIndexes_False_NoIndexCreated()
    {
        using var context = new ContextWithIndexCreationDisabled(CreateOptions(createIndexes: false));
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(ShortEntity))!;
        var indexes = entityType.GetIndexes().ToList();
        Assert.That(indexes, Is.Empty);
    }

    [Test]
    public void CreateIndexes_False_WithIndexName_ThrowsInvalidOperationException()
    {
        var exception = Assert.Throws<InvalidOperationException>(() =>
        {
            using var context = new ContextWithIndexCreationDisabledAndWithIndexName(CreateOptions(createIndexes: false));
            _ = context.Model;
        })!;

        Assert.That(exception.Message, Does.Contain("index creation is disabled"));
    }

    [Test]
    public void WithIndexName_CanBeChainedWithThenBy()
    {
        // Should not throw
        using var context = new ContextWithChainedIndexName(CreateOptions());
        _ = context.Model;

        // Verify the index was created with custom name and has all properties
        var entityType = context.Model.FindEntityType(typeof(MultiPropertyEntity))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        Assert.That(index, Is.Not.Null);
        Assert.That(index?.GetDatabaseName(), Is.EqualTo("IX_Multi_Custom"));
        Assert.That(index?.Properties.Select(p => p.Name), Is.EquivalentTo(["Category", "Priority"]));
    }

    [Test]
    public void StringWithNoMaxLength_SkipsIndex()
    {
        using var context = new ContextWithStringNoMaxLength(CreateOptions());
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(StringNoMaxLengthEntity))!;
        var indexes = entityType.GetIndexes().ToList();
        Assert.That(indexes, Is.Empty);
    }

    [Test]
    public void StringWithLargeMaxLength_SkipsIndex()
    {
        using var context = new ContextWithStringLargeMaxLength(CreateOptions());
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(StringLargeMaxLengthEntity))!;
        var indexes = entityType.GetIndexes().ToList();
        Assert.That(indexes, Is.Empty);
    }

    [Test]
    public void StringWithSmallMaxLength_CreatesIndex()
    {
        using var context = new ContextWithStringSmallMaxLength(CreateOptions());
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(StringSmallMaxLengthEntity))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        Assert.That(index, Is.Not.Null);
    }

    [Test]
    public void NonStringProperty_AlwaysCreatesIndex()
    {
        using var context = new ContextWithNonStringOrder(CreateOptions());
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(NonStringOrderEntity))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        Assert.That(index, Is.Not.Null);
    }

    [Test]
    public void CompositeIndex_WithStringNoMaxLength_SkipsIndex()
    {
        // Even if one property in a composite index is a string without max length,
        // the entire index is skipped
        using var context = new ContextWithMixedStringNoMaxLength(CreateOptions());
        _ = context.Model;

        var entityType = context.Model.FindEntityType(typeof(MixedStringNoMaxLengthEntity))!;
        var indexes = entityType.GetIndexes().ToList();
        Assert.That(indexes, Is.Empty);
    }
}

class ContextWithShortEntityName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .Property(_ => _.Name).HasMaxLength(450);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithLongEntityName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix> Entities => Set<EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix>()
            .Property(_ => _.Name).HasMaxLength(450);
        modelBuilder.Entity<EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithCustomIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere> Entities => Set<EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere>()
            .Property(_ => _.Name).HasMaxLength(450);
        modelBuilder.Entity<EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere>()
            .OrderBy(_ => _.Name)
            .WithIndexName("IX_LongEntity_Order");
    }
}

class ContextWithTooLongCustomIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .Property(_ => _.Name).HasMaxLength(450);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name)
            .WithIndexName(new('X', 129)); // 129 characters exceeds limit
    }
}

class ContextWithEmptyCustomIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .Property(_ => _.Name).HasMaxLength(450);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name)
            .WithIndexName("");
    }
}

class ContextWithChainedIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<MultiPropertyEntity> Entities => Set<MultiPropertyEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<MultiPropertyEntity>()
            .Property(_ => _.Category).HasMaxLength(450);
        modelBuilder.Entity<MultiPropertyEntity>()
            .OrderBy(_ => _.Category)
            .ThenBy(_ => _.Priority)
            .WithIndexName("IX_Multi_Custom");
    }
}

class ContextWithIndexCreationDisabled(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithIndexCreationDisabledAndWithIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name)
            .WithIndexName("IX_Custom");
    }
}

class ContextWithStringNoMaxLength(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<StringNoMaxLengthEntity> Entities => Set<StringNoMaxLengthEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<StringNoMaxLengthEntity>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithStringLargeMaxLength(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<StringLargeMaxLengthEntity> Entities => Set<StringLargeMaxLengthEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<StringLargeMaxLengthEntity>()
            .Property(_ => _.Name).HasMaxLength(1000);
        modelBuilder.Entity<StringLargeMaxLengthEntity>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithStringSmallMaxLength(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<StringSmallMaxLengthEntity> Entities => Set<StringSmallMaxLengthEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<StringSmallMaxLengthEntity>()
            .Property(_ => _.Name).HasMaxLength(200);
        modelBuilder.Entity<StringSmallMaxLengthEntity>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithNonStringOrder(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<NonStringOrderEntity> Entities => Set<NonStringOrderEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<NonStringOrderEntity>()
            .OrderBy(_ => _.Priority);
    }
}

class ContextWithMixedStringNoMaxLength(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<MixedStringNoMaxLengthEntity> Entities => Set<MixedStringNoMaxLengthEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<MixedStringNoMaxLengthEntity>()
            .OrderBy(_ => _.Priority)
            .ThenBy(_ => _.Name);
    }
}

public class ShortEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class MultiPropertyEntity
{
    public int Id { get; set; }
    public string Category { get; set; } = "";
    public int Priority { get; set; }
}

public class StringNoMaxLengthEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class StringLargeMaxLengthEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class StringSmallMaxLengthEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class NonStringOrderEntity
{
    public int Id { get; set; }
    public int Priority { get; set; }
    public string Name { get; set; } = "";
}

public class MixedStringNoMaxLengthEntity
{
    public int Id { get; set; }
    public int Priority { get; set; }
    public string Name { get; set; } = "";
}
