[TestFixture]
public class IndexNameTests
{
    static DbContextOptions CreateOptions() =>
        new DbContextOptionsBuilder()
            .UseSqlServer("Server=.;Database=Test;Trusted_Connection=True")
            .UseDefaultOrderBy()
            .Options;

    [Test]
    public void AutoGeneratedIndexName_WithinLimit_Succeeds()
    {
        // Should not throw - entity name is short
        using var context = new ContextWithShortEntityName(CreateOptions());
        _ = context.Model;

        // Verify the index was created with auto-generated name
        var entityType = context.Model.FindEntityType(typeof(ShortEntity))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        Assert.That(index, Is.Not.Null);
        Assert.That(index?.GetDatabaseName(), Is.EqualTo("IX_ShortEntity_DefaultOrder"));
    }

    [Test]
    public void AutoGeneratedIndexName_ExceedsLimit_ThrowsWithHelpfulMessage()
    {
        var exception = Assert.Throws<InvalidOperationException>(() =>
        {
            using var context = new ContextWithLongEntityName(CreateOptions());
            _ = context.Model;
        })!;

        Assert.That(exception.Message, Does.Contain("exceeds the maximum length of 128"));
        Assert.That(exception.Message, Does.Contain("WithIndexName()"));
    }

    [Test]
    public void CustomIndexName_WithinLimit_Succeeds()
    {
        // Should not throw
        using var context = new ContextWithCustomIndexName(CreateOptions());
        _ = context.Model;

        // Verify the index was created with custom name
        var entityType = context.Model.FindEntityType(typeof(EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        Assert.That(index, Is.Not.Null);
        Assert.That(index?.GetDatabaseName(), Is.EqualTo("IX_LongEntity_Order"));
    }

    [Test]
    public void CustomIndexName_ExceedsLimit_ThrowsArgumentException()
    {
        var exception = Assert.Throws<ArgumentException>(() =>
        {
            using var context = new ContextWithTooLongCustomIndexName(CreateOptions());
            _ = context.Model;
        })!;

        Assert.That(exception.Message, Does.Contain("exceeds maximum length of 128"));
    }

    [Test]
    public void CustomIndexName_NullOrEmpty_ThrowsArgumentException()
    {
        var exception = Assert.Throws<ArgumentException>(() =>
        {
            using var context = new ContextWithEmptyCustomIndexName(CreateOptions());
            _ = context.Model;
        })!;

        Assert.That(exception.Message, Does.Contain("cannot be null or whitespace"));
    }

    [Test]
    public void WithIndexName_CanBeChainedWithThenBy()
    {
        // Should not throw
        using var context = new ContextWithChainedIndexName(CreateOptions());
        _ = context.Model;

        // Verify the index was created with custom name and has all properties
        var entityType = context.Model.FindEntityType(typeof(MultiPropertyEntity))!;
        var index = entityType.GetIndexes().FirstOrDefault();
        Assert.That(index, Is.Not.Null);
        Assert.That(index?.GetDatabaseName(), Is.EqualTo("IX_Multi_Custom"));
        Assert.That(index?.Properties.Select(p => p.Name), Is.EquivalentTo(new[] { "Category", "Priority" }));
    }
}

class ContextWithShortEntityName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithLongEntityName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix> Entities => Set<EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix>()
            .OrderBy(_ => _.Name);
    }
}

class ContextWithCustomIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere> Entities => Set<EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere>()
            .OrderBy(_ => _.Name)
            .WithIndexName("IX_LongEntity_Order");
    }
}

class ContextWithTooLongCustomIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name)
            .WithIndexName(new string('X', 129)); // 129 characters exceeds limit
    }
}

class ContextWithEmptyCustomIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<ShortEntity> Entities => Set<ShortEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ShortEntity>()
            .OrderBy(_ => _.Name)
            .WithIndexName("");
    }
}

class ContextWithChainedIndexName(DbContextOptions options)
    : DbContext(options)
{
    public DbSet<MultiPropertyEntity> Entities => Set<MultiPropertyEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<MultiPropertyEntity>()
            .OrderBy(_ => _.Category)
            .ThenBy(_ => _.Priority)
            .WithIndexName("IX_Multi_Custom");
    }
}

public class ShortEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class EntityWithAnExtremelyLongNameThatWillDefinitelyExceedTheMaximumIndexNameLengthOfOneHundredTwentyEightCharactersWhenCombinedWithThePrefix
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class EntityWithVeryLongNameThatWouldExceedTheLimitIfWeDidNotUseCustomIndexNameHere
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}

public class MultiPropertyEntity
{
    public int Id { get; set; }
    public string Category { get; set; } = "";
    public int Priority { get; set; }
}
